name: app_icon_switcher
description: Application icon switcher, only works for android
version: 0.0.1
homepage: https://github.com/deynerreinoso/app_icon_switcher
#authors:
#  - deynerreinoso
#  - jhoanse7
environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.danyelssoft.app_icon_switcher
        pluginClass: AppIconSwitcherPlugin